bulletin_board/config/routes.rb
BulletinBoard::Engine.routes.draw do
  resources :boards
end

bulletin_board/app/models/bulletin_board/application_record.rb
module BulletinBoard
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

bulletin_board/app/models/bulletin_board/board.rb
module BulletinBoard
  class Board < ApplicationRecord
  end
end

bulletin_board/app/models/bulletin_board/comment.rb
module BulletinBoard
  class Comment < ApplicationRecord
  end
end

bulletin_board/app/controllers/bulletin_board/application_controller.rb
module BulletinBoard
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

bulletin_board/app/controllers/bulletin_board/boards_controller.rb
require_dependency "bulletin_board/application_controller"

module BulletinBoard
  class BoardsController < ApplicationController
    before_action :set_board, only: [:show, :edit, :update, :destroy]

    # GET /boards
    def index
      @boards = Board.all
    end

    # GET /boards/1
    def show
    end

    # GET /boards/new
    def new
      @board = Board.new
    end

    # GET /boards/1/edit
    def edit
    end

    # POST /boards
    def create
      @board = Board.new(board_params)

      if @board.save
        redirect_to @board, notice: 'Board was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /boards/1
    def update
      if @board.update(board_params)
        redirect_to @board, notice: 'Board was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /boards/1
    def destroy
      @board.destroy
      redirect_to boards_url, notice: 'Board was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_board
        @board = Board.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def board_params
        params.require(:board).permit(:title)
      end
  end
end

bulletin_board/app/helpers/bulletin_board/application_helper.rb
module BulletinBoard
  module ApplicationHelper
  end
end

bulletin_board/app/helpers/bulletin_board/boards_helper.rb
module BulletinBoard
  module BoardsHelper
  end
end

bulletin_board/app/views/bulletin_board/boards/_form.html.erb
<%= form_for(board) do |f| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bulletin_board/app/views/bulletin_board/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

bulletin_board/app/views/bulletin_board/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Boards</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.title %></td>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back MainApp', "/users" %>
<%= link_to 'New Board', new_board_path %>

bulletin_board/app/views/bulletin_board/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Back', boards_path %>

bulletin_board/app/views/bulletin_board/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @board.title %>
</p>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>

bulletin_board/app/views/layouts/bulletin_board/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bulletin board</title>
  <%= stylesheet_link_tag    "bulletin_board/application", media: "all" %>
  <%= javascript_include_tag "bulletin_board/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>